const Brands = [
  "Paris Corner",
  "Chanel",
  "Dior",
  "Guerlain",
  "Hermès",
  "Yves Saint Laurent",
  "Gucci",
  "Prada",
  "Louis Vuitton",
  "Tom Ford",
  "Giorgio Armani",
  "Valentino",
  "Versace",
  "Dolce & Gabbana",
  "Givenchy",
  "Burberry",
  "Bvlgari",
  "Jean Paul Gaultier",
  "Paco Rabanne",
  "Thierry Mugler",
  "Calvin Klein",
  "Ralph Lauren",
  "Hugo Boss",
  "Lancôme",
  "Estée Lauder",
  "Clinique",
  "Elizabeth Arden",
  "Marc Jacobs",
  "Carolina Herrera",
  "Viktor & Rolf",
  "Salvatore Ferragamo",
  "Issey Miyake",
  "Kenzo",
  "Azzaro",
  "Narciso Rodriguez",
  "Montblanc",
  "Tiffany & Co.",
  "Oscar de la Renta",
  "Chloé",
  "Cacharel",
  "Balenciaga",
  "Cartier",
  "Jo Malone",
  "Byredo",
  "Le Labo",
  "Maison Francis Kurkdjian",
  "Diptyque",
  "Acqua di Parma",
  "Creed",
  "Atelier Cologne",
  "Serge Lutens",
  "Amouage",
  "Roja Parfums",
  "Xerjoff",
  "Parfums de Marly",
  "Initio Parfums Prives",
  "By Kilian",
  "Juliette Has a Gun",
  "Frédéric Malle",
  "L'Artisan Parfumeur",
  "Penhaligon's",
  "Ormonde Jayne",
  "Mancera",
  "Montale",
  "Clive Christian",
  "Nasomatto",
  "Tauer Perfumes",
  "Etat Libre d'Orange",
  "Maison Margiela",
  "Nishane",
  "M. Micallef",
  "Parfums de Nicolai",
  "Houbigant",
  "Santa Maria Novella",
  "Orto Parisi",
  "Zoologist",
  "Slumberhouse",
  "The Different Company",
  "Arquiste",
  "Mona di Orio",
  "Miller Harris",
  "L'Occitane",
  "Lush",
  "Comme des Garçons",
  "Lorenzo Villoresi",
  "Reminiscence",
  "Aesop",
  "Bond No. 9",
  "Aerin",
  "Ajmal",
  "Rasasi",
  "Al Haramain",
  "Swiss Arabian",
  "Ard Al Zaafaran",
  "Arabian Oud",
  "Abdul Samad Al Qurashi",
  "Lattafa",
  "Al Rehab",
  "Maison Alhambra",
  "Maison Crivelli",
  "Mizensir",
  "Jovoy",
  "Vilhelm Parfumerie",
  "Coach",
  "Jimmy Choo",
  "Guess",
  "Abercrombie & Fitch",
  "Victoria's Secret",
  "Bath & Body Works",
  "Demeter",
  "Comptoir Sud Pacifique",
  "Yardley",
  "The Body Shop",
  "Fragonard",
  "Bois 1920",
  "Loewe",
  "Paloma Picasso",
  "Anais Anais",
  "Jean Patou",
  "Maison Louis Marie",
  "Maitre Parfumeur et Gantier",
];

export default Brands;
